### ISSUE TITLE
脚本ssl请求问题

### ISSUE THREAD

**Issue by biexiang** [OrzGeeker/OrzMC#2]
Use Local File For Game Version Manifest JSON File
Download Game Json Configure File!
Downloading the client jar file ...
Client Download Completed!
Download assetIndex JSON File
assets objects: 100% (2110 of 2110) |###################################################################| Elapsed Time: 1:09:56 Time:  1:09:56
641/2110(minecraft/sounds/entity/shulker/shoot2.ogg)FAILED!
661/2110(minecraft/sounds/entity/squid/death3.ogg)FAILED!
1553/2110(minecraft/sounds/mob/slime/big3.ogg)FAILED!
1985/2110(realms/lang/da_dk.json)FAILED!
2006/2110(realms/lang/esan.json)FAILED!
libraries:  70% (40 of 57) |#####################################################                       | Elapsed Time: 0:01:34 ETA:   0:00:19
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 344, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 843, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 370, in connect
    ssl_context=context)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 355, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='libraries.minecraft.net', port=443): Max retries exceeded with url: /ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0-natives-osx.jar (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1056)')))

During handling of the above exception, another exception occurred:

导致lib文件没下载下来，也不重新下载，启动直接报异常

Not Exist: /Users/poly/minecraft/versions/1.15.2/client/pure/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
Not Exist: /Users/poly/minecraft/versions/1.15.2/client/pure/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
Not Exist: /Users/poly/minecraft/versions/1.15.2/client/pure/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
Not Exist: /Users/poly/minecraft/versions/1.15.2/client/pure/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
Not Exist: /Users/poly/minecraft/versions/1.15.2/client/pure/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
Not Exist: /Users/poly/minecraft/versions/1.15.2/client/pure/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
Not Exist: /Users/poly/minecraft/versions/1.15.2/client/pure/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
➜  Desktop Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:808)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:443)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:65)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:349)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:348)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:430)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:326)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:588)

**Comment by wangzhizhou** [comment]
Should use vpn

**Comment by wangzhizhou** [comment]
Update OrzMC version

**Comment by wangzhizhou** [comment]
现在使用的OrzMC是什么版本

**Comment by wangzhizhou** [comment]
现在已经改了实现，使用python3 运行就可以了
